### ISSUE TITLE
Driving AI App

### ISSUE THREAD

**Issue by databake** [react-ui-kit/dribbble2react#14]
It would appear that all the icons that should be in ` /assets/images/Icon` are missing.

**Comment by hetmann** [comment]
@databake I double checked, yes they don't appear to be in the repository. As you can see in PRs or commits I added all the files but for some reason they are not showing or are not added in the repository.

One reason could be: Microsoft bought GitHub and now they screwed all the good things (same with Skype)

**Comment by hetmann** [comment]
@databake fixed
