### ISSUE TITLE
Camping Spots Finder App

### ISSUE THREAD

**Issue by Angelk90** [react-ui-kit/dribbble2react#19]
Hi @hetmann , congratulations for the projects, I'm trying them out.
I tried "Camping Spots Finder App", on android even if the design is not made for Android I would advise you to try it.
I noticed a minimal thing, but if one has an expert eye, he notices it.
In the menu part, "all, Tenting, Rv camping", the color of the menu does not take everything but leaves a minimum space of 1px, which in my opinion from a little disturbance, is more noticeable in the part where there are the parts rounded.
Not if a problem due to an external module but I report it anyway.

I uploaded an image:

![image](https://user-images.githubusercontent.com/20476002/54936805-86786e80-4f23-11e9-8fb8-399adbeaf591.png)

Link expo: https://snack.expo.io/rkPMlKIu4

P.Š.
I would advise you in the future that when you load a new project, you will also upload the parts to expo.
So users can try a demo version even without having to load them.

I suggest you put the link I created for expo in the readme of the project.

**Comment by hetmann** [comment]
Expo snack: https://snack.expo.io/@react-ui-kit/camping-spots-finder-app
