### ISSUE TITLE
Travel Article Application

### ISSUE THREAD

**Issue by nelsonprsousa** [react-ui-kit/dribbble2react#2]
**Travel Article Application**

**Collection of images:**
https://dribbble.com/shots/5729892-Travel-Article-Application
https://dribbble.com/shots/5717917-Travel-Article-Application
https://dribbble.com/shots/5774759-Photo-Album-Application

**Comment by hetmann** [comment]
@NelsonPRSousa nice one, the design is beautiful :) 
The animations & transitions are the biggest challenge. I'll add this one to the list.

**Comment by nelsonprsousa** [comment]
> @NelsonPRSousa nice one, the design is beautiful :)
> The animations & transitions are the biggest challenge. I'll add this one to the list.

Glad you like it! Btw, are you using just React Native or an toolchain like Expo.io?

Let me know if you need more suggestions and how can I help 👍

**Comment by hetmann** [comment]
Expo.io for fast setup and testing, but I use to code the screens and components using react-native components, trying to exclude Expo API as much as possible.

**Comment by nelsonprsousa** [comment]
Let me know if you need any help!

**Comment by hetmann** [comment]
Added to the list.

**Comment by hetmann** [comment]
@NelsonPRSousa Just to let you know that I pushed the Travel App screens to https://github.com/react-ui-kit/dribbble2react/tree/master/travel-app

Next is the video for coding session :)

**Comment by hetmann** [comment]
@NelsonPRSousa here is the video: https://youtu.be/zJ9QETiwdfo

**Comment by nelsonprsousa** [comment]
Will take close attention. Thanks!
