### ISSUE TITLE
Quote - chat layaout

### ISSUE THREAD

**Issue by ciaoamigoschat** [react-ui-kit/dribbble2react#24]
**Name your screen design**
mychat

**Share the design source / link**
https://dribbble.com/shots/5557158-Rainbow-Messenger-flow

You can give me a quote?

**Comment by hetmann** [comment]
Hi @ciaoamigoschat 
Thanks for sharing app UI design. At the first glance this is very beautiful & complex UI.
As they didn't shared a HD detailed image for each screen is hard to reverse engineering the design, but not impossible.

**Dashboard + Profile**: https://dribbble.com/shots/5528852-Rainbow-Messenger
**Chat + Preview Chats**: https://dribbble.com/shots/5528867-Rainbow-Messenger-chat-view
**Dark / White**: https://dribbble.com/shots/5567452-Rainbow-Messenger-Dark-and-White
**Animations**: https://dribbble.com/shots/5567430-Rainbow-Messenger-Animation

Raw estimation breakdown:
- **UI**: 24-32h
- **Animations**: 24-48h
- **Functionalities**: 24h

**Total: 72-104 hours**

**Comment by ciaoamigoschat** [comment]
can someone help me do it? Cost?

**Comment by hetmann** [comment]
> can someone help me do it? Cost?

Write me a message to **contact@react-ui-kit.com** with all your requirements including the budget, and we'll have someone helping your do this.

**Comment by ciaoamigoschat** [comment]
OK THANKS.
