### ISSUE TITLE
Travel-app

### ISSUE THREAD

**Issue by Franzandr** [react-ui-kit/dribbble2react#25]
![WhatsApp Image 2019-04-03 at 15 32 24](https://user-images.githubusercontent.com/8989506/55514625-d93dde80-5625-11e9-9077-4ff7abf73e77.jpeg)
What's the Problem with the Android version?.

**Comment by hetmann** [comment]
Hey, thanks for sharing this. Is not tested on Android. I’ll have a look in the weekend.

**Comment by Franzandr** [comment]
thank you, i Think the Problem is with the header: {}. Also in android the negative padding gives errors in destinationInfo bottom:

**Comment by hetmann** [comment]
@Franzandr can you create a PR with the fix?

**Comment by Franzandr** [comment]
@hetmann `static navigationOptions = {
    title: 'Home',
    headerStyle: {
      backgroundColor: '#fff',
    }
    // header: (
    //   <View style={[styles.flex, styles.row, styles.header,]}>
    //     <View>
    //       <Text style={{ color: theme.colors.caption }}>Search for place</Text>
    //       <Text style={{ fontSize: theme.sizes.font * 2 }}>Destination</Text>
    //     </View>
    //     <View>
    //       <Image style={styles.avatar} source={{ uri: 'https://randomuser.me/api/portraits/women/32.jpg'}} />
    //     </View>
    //   </View>
    // )
  };`

**Comment by Franzandr** [comment]
@hetmann 
![Screen Shot 2019-04-11 at 12 54 48](https://user-images.githubusercontent.com/8989506/55979974-08250780-5c59-11e9-968d-445aba302654.png)
