### ISSUE TITLE
Demos not working

### ISSUE THREAD

**Issue by satvikmaker** [react-ui-kit/dribbble2react#27]
The expo demo's and the app is crashing on Android (Galaxy S7 Edge) for few of the apps - Smart Home, Driving AI assistant to name a couple of them.

**Comment by hetmann** [comment]
@bozzmob thank you for pointing this out. Some of the apps are not tested on Android. Sorry for that, if you can help with this you can create a PR.
The apps are open-source, so anyone can help improve the code.
