### ISSUE TITLE
Needs more documentation.

### ISSUE THREAD

**Issue by karimcambridge** [react-ui-kit/dribbble2react#29]
* Testing the plant-app*

Okay, so I thought setup would be very simple, (drop files in a `create-react-native-app`, then `npm install` then `react-native run-android`?

That fails with:

```
PS D:\Github\appname> react-native link
D:\Github\appname\node_modules\@babel\core\lib\config\files\plugins.js:152
    throw e;

Error: Cannot find module 'metro-react-native-babel-preset' from 'D:\Github\appname'
```

Also what is `metro-react-native-babel-preset`? where should that go

---

Also `screens/Signup.js` should be `screens/SignUp.js`

---

Unable to resolve "react-native-gesture-handler" from "node_modules\@react-navigation\native\src\Scrollables.js" < on `expo start` -> run on android emulator, that should be in package.json

**Comment by hetmann** [comment]
@karimcambridge good point.
- what app are you getting this errors?
- all the apps/screens are based on `expo init` for my fast setup

Mainly the screens are for inspirational purpose, you just copy/paste full code or a partial code.

**Comment by karimcambridge** [comment]
Yea I just pulled the code.

Ah, I may be at fault here, I BELIEVE this folder was a `create-react-native-app` command and not an `expo init`, I shall start from fresh and try that!

**Comment by hetmann** [comment]
@karimcambridge let me know if is working or if I need to update the project.

**Comment by karimcambridge** [comment]
![image](https://user-images.githubusercontent.com/4283893/56576436-bce6ef00-659e-11e9-9749-e937f86fc09f.png)
In get this after doing

`expo init`
Adding all files & package.json.
`npm install`
`npm start`.

**Comment by raymclee** [comment]
In screens\welcome.js

 <Modal animationType="slide" visible={this.state.showTerms} onRequestClose={() => this.setState({ showTerms: false })}>

**Comment by hetmann** [comment]
@karimcambridge according to @cheuk3 you could add a new prop => `onRequestClose={ () => {} }`

**Comment by hetmann** [comment]
@karimcambridge the issue is fixed, please try again.
@cheuk3 thanks for the support

**Comment by arkhan13** [comment]
for the error about react-native-gesture handler 

just go to your root project and on terminal run

expo install react-native-gesture-handler
