### ISSUE TITLE
UI bug with plant app

### ISSUE THREAD

**Issue by karimcambridge** [react-ui-kit/dribbble2react#30]
![image](https://user-images.githubusercontent.com/4283893/56583808-cbd69d00-65b0-11e9-8131-3393a9b07fea.png)

When clicking on an input, it pushes everything into the top..

just reporting it, up to you if u wanna fix it.

**Comment by hetmann** [comment]
@karimcambridge what device you're using?

**Comment by karimcambridge** [comment]
Pixel 2, Android Pie

**Comment by hetmann** [comment]
@karimcambridge thanks, I'll take a look
