### ISSUE TITLE
Undefined error in Block component

### ISSUE THREAD

**Issue by iloveyii** [react-ui-kit/dribbble2react#35]
In your plant-app, while learning as soon as I import {Block} from components I get the following error on snack.expo project:

Device: (101:380) Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

This error is located at:
    in App
    in RCTView
    in RCTView
https://snack.expo.io/@alibth/plants

**Comment by hetmann** [comment]
@iloveyii Thanks for opening this issue. Usually this should work, but I double check this snack and probably the error is in the App setup, don't know exactly.

Try this: `import Block from './components/Block';`

Also please copy the **theme.js** because the **Block** component is using it.
