### ISSUE TITLE
Error Code:500

### ISSUE THREAD

**Issue by edy500** [react-ui-kit/dribbble2react#38]
I'm unfortunately with a Error 500, App.js. Unable to resolve module 'expo'. Does not exist in the Haste module map.  I used the code from github. Tks.

"dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.9",
    "react-native-gesture-handler": "^1.3.0",
    "react-navigation": "^3.11.0",
    "react-redux": "^7.0.3",
    "redux": "^4.0.1",
    "redux-thunk": "^2.3.0"

**Comment by hetmann** [comment]
@edy500 thanks, I just replied to your youtube comment.

Is because I'm using **expo** for:
- **LinearGradient** in screens/Explore.js, components/Button.js, components/Progress.js
- **Icon** in components/Input.js

My suggestion is to refactor the screens & components to exclude expo.

**Comment by hetmann** [comment]
@edy500 can you provide any feedback if the problem persists?

**Comment by edy500** [comment]
Hi, I'm newbie with React Native, I ran with Expo using my smatphone. First appear "Your home Greener." screen with logo properly, but some seconds later comes a Error code:500, "Unable to resolve module react-navigation C:\\...\\navigation\\index.js". Module 'react-navigation' does not exist in the Haste module map."
I tried complete code as well, and the error is the same.
Should appear "Welcome" like in 33:10 min. in the video.

App.js
==========
import React, {Component} from 'react';

import {Platform, StyleSheet, Text, View} from 'react-native';

import { AppLoading, Asset } from 'expo';

import Navigation from './navigation';

import { Block } from './components';

// import all used images
const images = [
  require('./assets/icons/back.png'),
  require('./assets/icons/plants.png'),
  require('./assets/icons/seeds.png'),
  require('./assets/icons/flowers.png'),
  require('./assets/icons/sprayers.png'),
  require('./assets/icons/fertilizers.png'),
  require('./assets/images/plants_1.png'),
  require('./assets/images/plants_2.png'),
  require('./assets/images/plants_3.png'),
  require('./assets/images/explore_1.png'),
  require('./assets/images/explore_2.png'),
  require('./assets/images/explore_3.png'),
  require('./assets/images/explore_4.png'),
  require('./assets/images/explore_5.png'),
  require('./assets/images/avatar.png'),
];
export default class App extends React.Component {
  state = {
    isLoadingComplete: false,
  }

handleResourcesAsync = async () => {
  //we're caching all the images
  // for better performance on the app
  const cacheImages = images.map(img => {
    return Asset.fromModule(image).downloadAsync();
  });
  return Promise.all(cacheImages);
}
  render() {
    if(this.state.isLoadingComplete && !this.props.skipLoadingScreen) {
      return (
        <AppLoading
          startAsync={this.handleResourcesAsync}
          onError={error => console.warn(error)}
        onFinish={() => this.setState({ isLoadingComplete: true })}
        />
        )
    }
    return (
      <Block white>
        <Navigation />
      </Block>
    );
  }
}

const styles = StyleSheet.create({
   
  
});


====================
Index.js
=================
import React from 'react';
import { Image } from 'react-native';
import { createAppContainer, createStackNavigator } from 'react-navigation';

import Welcome from '../screens/Welcome';
//import Login from '../screens/Login';
//import Explore from '../screens/Explore';
//import Browse from '../screens/Browse';
//import Product from '../screens/Product';
//import Settings from '../screens/Settings';

import { theme } from '../constants';


const screens = createStackNavigator({

    Welcome,
    
    //Login,
    //Explore,
    //Browse,
    //Product,
    //Settings,


}, {
  defaultNavigationOptions:{

    headerStyle: {},
    headerBackImage: <Image />,
    headerBackTitle: null, 
    headerLeftContainerStyle: {},
    headerRightContainerStyle: {},
  }
});

export default createAppContainer(screens);

**Comment by hetmann** [comment]
You should install "react-navigation" as this is a dependency of the project.
Did you tried clone the project, install all deps and run it with expo?
