### ISSUE TITLE
Plant app bugs (undefined is not an object (evaluating 'theme.label'))

### ISSUE THREAD

**Issue by Oguntoye** [react-ui-kit/dribbble2react#46]
TypeError: TypeError: undefined is not an object (evaluating 'theme.label')

**Comment by hetmann** [comment]
@Oguntoye thanks to point this out. I wasn't able to find the error or any reference to it.
Could you describe the exact steps? or anything else that will help investigate this, screen & line number?

**Comment by Oguntoye** [comment]
Thanks for your response.

Steps
0.  Download the project zipped file
1.   npm install and that installs all the dependencies
2.   expo start --android
3.   Opened application on android emulator
4.   Welcome page displayed
5.   Press Login or Signup (Red screen error TypeError: TypeError: undefined is not an object (evaluating 'theme.label'))

**Comment by naveedahmed986** [comment]
I faced the same issue. 
Steps: 
1. npm install
2. npm start
3. Opened application on iPhone 7 using Expo CLI
4. Welcome screen is displayed
5. Press Login or Signup (Red screen error TypeError: TypeError: undefined is not an object (evaluating 'theme.label'))

**Comment by Oguntoye** [comment]
> I faced the same issue.
> Steps:
> 
> 1. npm install
> 2. npm start
> 3. Opened application on iPhone 7 using Expo CLI
> 4. Welcome screen is displayed
> 5. Press Login or Signup (Red screen error TypeError: TypeError: undefined is not an object (evaluating 'theme.label'))

Have you been able to resolve this?

**Comment by hetmann** [comment]
@Oguntoye @naveedahmed986 I followed the same steps without any errors. What setups do you have: npm, yarn, nodejs, react-native, etc?

**Comment by Oguntoye** [comment]
npm
Node v 10.15.1
react-native-cli : 2.0.1

**Comment by hetmann** [comment]
@Oguntoye could you share a screenshot of the error on simulator?

**Comment by Oguntoye** [comment]
@hetmann 
Steps to reproduce:
1. Download a compressed zip of https://github.com/react-ui-kit/dribbble2react/tree/master/plant-app
2. npm install
3. expo start --android

After expo start --android
![Screen Shot 2019-08-29 at 1 53 07 PM](https://user-images.githubusercontent.com/25712020/63946326-75003900-ca64-11e9-9bea-74b7a7f77a7d.png)

When I press login or sign up
![Screen Shot 2019-08-29 at 1 53 24 PM](https://user-images.githubusercontent.com/25712020/63946373-8fd2ad80-ca64-11e9-8b28-6642da2f850b.png)

**Comment by ahunain** [comment]
@hetmann 
I also have the same problem

**Comment by hetmann** [comment]
@Oguntoye @ahunain @naveedahmed986 

I think this is due to `react-navigation`, from the screenshot I understand this:
- **HeaderTitle** is rendering the title (in our case nothing) from **Header.tsx** and is trying to get the `theme.label` value, but the theme is **undefined**.

My suggestion is to edit the screens/**Signup.js** & screens/**Login.js** add the following:
```
static navigationOptions = {
    title: null
}
```
This will tell **HeaderTitle** not to render any **title** and maybe will ignore that `theme.label` error.

**Comment by Oguntoye** [comment]
@hetmann ..
I added the above snippet but the error still persists

**Comment by naveedahmed986** [comment]
I also added the snippet but error is still there

I tried to locate the file that it indicates where error is coming from 
node_modules\react-navigation-stack\lib\module\views\Header\HeaderTitle.js:20
and on  line 20 :         

style={[styles.title, { color: theme.label }, style]}

i tried changing it to color: '#3c4043' but still gives the same error.


> @Oguntoye @ahunain @naveedahmed986
> 
> I think this is due to `react-navigation`, from the screenshot I understand this:
> 
> * **HeaderTitle** is rendering the title (in our case nothing) from **Header.tsx** and is trying to get the `theme.label` value, but the theme is **undefined**.
> 
> My suggestion is to edit the screens/**Signup.js** & screens/**Login.js** add the following:
> 
> ```
> static navigationOptions = {
>     title: null
> }
> ```
> 
> This will tell **HeaderTitle** not to render any **title** and maybe will ignore that `theme.label` error.

**Comment by hetmann** [comment]
@naveedahmed986 @Oguntoye @ahunain 
What version of **react-navigation** && **react-navigation-stack** you're using?

You can find the version on package.json:
- node_modules/react-navigation/package.json
- node_modules/react-navigation-stack/package.json

I followed the steps above (download and install) I have the following versions:
- **react-navigation** > 3.6.1
- **react-navigation-stack** > 1.2.0

HeaderTitle.tsx is looking like this:
<img width="573" alt="Screenshot 2019-08-30 at 14 41 56" src="https://user-images.githubusercontent.com/3584560/64018188-64b78f00-cb34-11e9-80c8-1937f0676b70.png">

**Comment by jestintab** [comment]
I am also having the same issue.

**Comment by hetmann** [comment]
@jestintab waiting for the response to my question:
- What version of react-navigation && react-navigation-stack you're using?

**Comment by jestintab** [comment]
@hetmann react-navigation version is 3.6.1 and react-stack-navigation was 1.2.5 , I reinstalled to 1.2.0 still it doesn't work

**Comment by hetmann** [comment]
@Oguntoye @naveedahmed986 @ahunain @jestintab 
- what OS are you guys using:  Windows, Mac or Linux?

**Comment by priteshbaviskar** [comment]
I use Mac and I ran into the same thing.

**Comment by Oguntoye** [comment]
I'm using MAC OSX High Sierra

**Comment by hetmann** [comment]
@Oguntoye @naveedahmed986 @ahunain @jestintab 
I think I found a solution for this problem, this is due to expo versions:
- Try to migrate from expo31 to expo33. Skip expo32.

https://stackoverflow.com/questions/57768921/typeerror-typeerror-undefined-is-not-an-object-evaluating-theme-label-erro

**Comment by priteshbaviskar** [comment]
> @Oguntoye @naveedahmed986 @ahunain @jestintab
> I think I found a solution for this problem, this is due to expo versions:
> 
>     * Try to migrate from expo31 to expo33. Skip expo32.
> 
> 
> https://stackoverflow.com/questions/57768921/typeerror-typeerror-undefined-is-not-an-object-evaluating-theme-label-erro

This worked! Much thanks :)

**Comment by hetmann** [comment]
@Oguntoye @naveedahmed986 @ahunain @jestintab 
I leave this issue open so other can see the solution.

**Comment by Oguntoye** [comment]
Thanks so much. I will check it our later

**Comment by adogth** [comment]
Hi i fixed the react navigation in navigation/index with 
`import { createAppContainer } from "react-navigation";
import { createStackNavigator } from "react-navigation-stack";`

**Comment by ThPch** [comment]
> import { createAppContainer } from "react-navigation"; import { createStackNavigator } from "react-navigation-stack";

Doesn't work for me

**Comment by hetmann** [comment]
@ThomasPerche I need to update this app to the latest version for react-navigation and expo

**Comment by Oguntoye** [comment]
I've personally find this react navigation too bugy.. quite okay with react
native navigation...

Must more stable and also better in performance wise.

**Comment by hetmann** [comment]
@Oguntoye the v5 of react-navigation is much better compared to < v4
I like the new approach, component based and more like ReactJS style :)

**Comment by Jyzzi** [comment]
hello, i also ahve the problem with theme.label
i have already update my dependencies
![Capture2](https://user-images.githubusercontent.com/46704276/72219367-9b230300-3545-11ea-90cf-9d44c355241b.PNG)
![Capture](https://user-images.githubusercontent.com/46704276/72219368-9b230300-3545-11ea-8812-1c91e6add841.PNG)

i need help please ..

**Comment by Jyzzi** [comment]
> hello, i also ahve the problem with theme.label
> i have already update my dependencies
> ![Capture2](https://user-images.githubusercontent.com/46704276/72219367-9b230300-3545-11ea-90cf-9d44c355241b.PNG)
> ![Capture](https://user-images.githubusercontent.com/46704276/72219368-9b230300-3545-11ea-8812-1c91e6add841.PNG)
> 
> i need help please ..

my code : 

`import { createAppContainer } from 'react-navigation';
import { createStackNavigator } from 'react-navigation-stack';
import Home from "./screens/Home";



const AppNavigator = createStackNavigator({
  Home: {
    screen: Home,
  },
});

export default createAppContainer(AppNavigator);`


`import React from 'react';
import { View, Text } from 'react-native';
import { createAppContainer } from 'react-navigation';
import { createStackNavigator } from 'react-navigation-stack';

class Home extends React.Component {
    static navigationOptions = {
      title: 'Home',
    };
  render() {
    return (
      <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
        <Text>Home Screen</Text>
      </View>
    );
  }
}

export default Home`

**Comment by hetmann** [comment]
@Oguntoye @naveedahmed986 @ahunain @jestintab @ThomasPerche @priteshbaviskar  all the apps have been updated to use Expo SDk 36. This should fix all the errors.

**Comment by coderDancer** [comment]
> @ThomasPerche I need to update this app to the latest version for react-navigation and expo

 I update this app to the right version for react-navigation ,  go well finally
