### ISSUE TITLE
Responsive Screen

### ISSUE THREAD

**Issue by Moamber** [react-ui-kit/dribbble2react#51]
i just start using your react kit. You give static size in theme how it well in all phones (big, small).
how you achieve consistent app design across different size of phones.

**Comment by hetmann** [comment]
Hey @Moamber thank you for using it.

Responsive is based on **flex style** so you can use the Block/View component and make it responsive based on flex: 1 or 2 etc.
The theme **SIZES** are used for **fontSize**, **padding**, **margin**, etc.
