### ISSUE TITLE
Pathfinder

### ISSUE THREAD

**Issue by CristinaMrtn** [react-ui-kit/dribbble2react#52]
**Name your screen design**
Let me know the title/name, e.g.: My Custom App

**Share the design source / link**
Let me know the design source or link (preferable from dribbble)

**Comment by hetmann** [comment]
@CristinaMrtn thank you for your suggestion. Could you share an example app link?

**Comment by hetmann** [comment]
@CristinaMrtn closing this for the lack of app link example. You can reopen this with a comment :)
