### ISSUE TITLE
Plant app header

### ISSUE THREAD

**Issue by modasto** [react-ui-kit/dribbble2react#58]
![WhatsApp Image 2020-01-21 at 02 02 35](https://user-images.githubusercontent.com/19765855/72764905-a84d8b00-3bf2-11ea-8db0-fe037356b470.jpeg)
trying to align the back button and login text on the header but failing, padding-top is higher than the bottom?

**Comment by hetmann** [comment]
@modasto can you share your current code to take a look?

**Comment by modasto** [comment]
import React from "react";
import { Image } from "react-native";
import { createAppContainer } from "react-navigation";
import { createStackNavigator } from "react-navigation-stack";

import Welcome from '../screens/Welcome';
import Login from '../screens/Login';
import SignUp from '../screens/SignUp';
import Forgot from '../screens/Forgot';
import Explore from '../screens/Explore';
import Product from '../screens/Product';
import Settings from '../screens/Settings';
import Resources from '../screens/resources/Resources';

import { theme } from "../constants";

const screens = createStackNavigator(
  {
    Welcome,
    Login,
    SignUp,
    Forgot,
    Explore,
    Product,
    Settings,
    Resources,
  },
  {
  defaultNavigationOptions: ({navigation}) => ({
    headerStyle: {
      elevation: 0, // for android
    },
    title: `${navigation.getParam('appBar', {title: ''}).title}`,
    headerTitleContainerStyle: {
      alignItems: 'center',
    },
    headerLeftContainerStyle: {
      alignItems: 'center',
      marginLeft: theme.sizes.base * 1,
      paddingRight: theme.sizes.base,
    },
    headerRightContainerStyle: {
      alignItems: 'center',
      paddingRight: theme.sizes.base,
    },
  })
});

export default createAppContainer(screens);

**Comment by hetmann** [comment]
@modasto you can play around with **headerStyle** for each screen or **defaultNavigationOptions**.

What I found is that you can add height to **headerStyle** and the content will be aligned to middle.

**react-navigation** uses **SafeAreaView** and that is why you see there is more space on the top compared to bottom.

Example
```js
headerStyle: {
  height: 100,
  elevation: 0 // for android
},
```

![Screenshot 2020-01-21 at 14 15 30](https://user-images.githubusercontent.com/3584560/72804423-fe551980-3c58-11ea-80b7-32ba742e9ae4.png)

**Comment by modasto** [comment]
ok, thanks
