### ISSUE TITLE
Parking APP: Err 500 Unable to resolve "./screens/Map" from "App.js

### ISSUE THREAD

**Issue by kiwenoob** [react-ui-kit/dribbble2react#59]
**Parking APP**

Hi,

Many thanks for this project, I have the following error: 
"Unable to resolve "./screens/Map" from "App.js"
Failed building JavaScript bundle."

Please see below the screenshot on emulator. Can you please help?
<img width="337" alt="Screenshot 2020-01-21 at 17 52 16" src="https://user-images.githubusercontent.com/60131978/72829731-3e2af980-3c77-11ea-9a2e-73318bd78c1d.png">

:D Thanks!

**Comment by hetmann** [comment]
Hey @kiwenoob ... it seems that the file is missing from screens/Map.js. Can you check that?

Here is the current repo for parking-app
<img width="1009" alt="Screenshot 2020-01-21 at 20 40 50" src="https://user-images.githubusercontent.com/3584560/72832931-72f67b00-3c8e-11ea-92a3-ceb535b6dbd5.png">

**Comment by kiwenoob** [comment]
Hi @hetmann 
the issue is that screens/Map.js is present in the directory.

**Comment by hetmann** [comment]
@kiwenoob can you show me a screenshot of the App.js file and the folder structure?

**Comment by GermaVinsmoke** [comment]
I'm getting this error in Expo snack 
![image](https://user-images.githubusercontent.com/32815509/87881117-c7e43580-ca14-11ea-8231-d3eea1023957.png)

**Comment by Rizialdi** [comment]
Hi,
Did you try installing it manually ?

```cmd
expo add react-native-maps
```

Hope this helps.
