### ISSUE TITLE
Build errors - unable to resolve react-native-screens

### ISSUE THREAD

**Issue by satvikmaker** [react-ui-kit/dribbble2react#62]
This error is across all the apps.

Error that's seen in velocity-
```
Unable to resolve "react-native-screens" from "node_modules/react-navigation-drawer/lib/module/views/DrawerView.js"
```

Solution: add
```
"react-native-screens": "^2.0.0-beta.7",
```
in all the app's `package.json`.

I can work on the PR for this over the end of the day.

**Comment by hetmann** [comment]
@bozzmob probably this is due to react-navigation updates. Thanks for spotting this :)
Is time consuming for just me to update all the packages. Waiting for your PR.
