### ISSUE TITLE
Using RN CLI Exception

### ISSUE THREAD

**Issue by Namec** [react-ui-kit/dribbble2react#69]
When copying the Project Driving to a fresh RN CLI project, i imported all the necessary packages and updated some files accordigly

but when executing it gives me a error :

You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports. Check the render method of 'Welcome'

Any help will be appreciated

**Comment by alenthomas678** [comment]
It's just a simple error, it is actually with your import statements, may be you haven't used { } to include the required component. Just show the code snippet of your import.

**Comment by hetmann** [comment]
@Namec can you share with us any errors screenshots?

**Comment by Namec** [comment]
@alenthomas678 currently i haven't changed any export or import statement, just copy and paste from an Expo project to an RN Cli project

@hetmann the screenshot currently doesnt offer more information thant this message :

You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports. Check the render method of 'Welcome'

**Comment by alenthomas678** [comment]
Did you clone the project or just copy paste the code from github and inserted into the files in folders which you created your own. If that the case, you have messed up something within your files and they were not properly imported.

**Comment by Namec** [comment]
Currently i just copied the files, since Expo eject can lead to worst problems
